### ISSUE TITLE
cloudify-stage-4.3.0  

### ISSUE THREAD

**Issue by fanzhengweiwudi** [cloudify-cosmo/cloudify-stage#1681]
execute npm run beforebuild  ；
npm install  error；

![I`%{Q)3@ISLU9VR}V @SH%I](https://user-images.githubusercontent.com/49433466/143374173-7f8bdbd0-5cd7-4fbb-b4f2-76f61b3dbe8a.png)

![W_TI 2F`V`WJ2$3KJ5(@JKW](https://user-images.githubusercontent.com/49433466/143374177-461efdb5-48ea-4b36-b8f9-b335bc7c20cb.png)

**Comment by qooban** [comment]
@fanzhengweiwudi According to https://cloudify.co/cloudify-lifecycle/ Cloudify v4.3 is no longer supported, so we are not planning any changes for v4.3. Please switch to a newer version.
