### ISSUE TITLE
Unable to open UI for Community AIO image

### ISSUE THREAD

**Issue by kspviswa** [cloudify-cosmo/cloudify-stage#869]
Tried to follow the demo from https://cloudify.co/getting-started/ , but unable to open Cloudify Manager UI. PFB JS console error that is preventing from rending UI

<img width="554" alt="Screen Shot 2019-09-29 at 7 27 46 PM" src="https://user-images.githubusercontent.com/7476271/65842236-ab450880-e2ef-11e9-80e1-d0cf02cbe195.png">

**Comment by qooban** [comment]
@kspviswa Thank you for reporting the issue. I reproduced the problem, working on the fix.

Please be aware that we are not using GitHub issues for handling such cases, so I created an issue in our issue tracking system: https://cloudifysource.atlassian.net/browse/CY-1781 . I'm closing Github issue.

For the future - please use our Slack channel: https://cloudify.co/slack/ to ask for support or report issues.
