### ISSUE TITLE
First Issue: demo running in local, some wrong happened, can't jump from loginpage

### ISSUE THREAD

**Issue by ToTheEnd0314** [cloudify-cosmo/cloudify-stage#876]
### Follow your(the author) guide, but get follow problem:
when I enter username and password, click <Login> button, show a tip say 👇
```
Failed to authenticate with manager: socket hang up
```
And nothing happened...

#### Env
```
cloudify-stage: v5.0.5-.dev1;
node: v10.16.0
postgres: v12
```
1. me.json
```
{
  "app": {
      "influx": {
        "ip" : "127.0.0.1"
      },
      "ssl": {
        "ca": null
      }
  },
  "manager": {
    "ip":"127.0.0.1",
    "protocol" : "http",
    "port": "5432" // postgres server port
  },
  "e2e": {

  }
}
```
2. conf/app.json
```
......
"ssl": {
    "ca": "" // Because error say can't find ***.pem file, so......
  },
......
```
3. webpack.config.js (CopyWebpackPlugin)
```
    // {
    //     from: 'userData',
    //     to: 'userData'
    // }

    /* Because when run devServer, get an error say , can't find "serData" */
```

## Something wrong? And Please Tell Me ... ... Thank You!

**Comment by qooban** [comment]
@ToTheEnd0314 , thank you for reporting the issue. 

> 1. me.json
> ```
> {
>   "app": {
>       "influx": {
>         "ip" : "127.0.0.1"
>       },
Please update your `me.json` according to latest [me.json.template](https://github.com/cloudify-cosmo/cloudify-stage/blob/master/conf/me.json.template). There's no `influx` object inside.

>  "manager": {
>     "ip":"127.0.0.1",
>     "protocol" : "http",
>     "port": "5432" // postgres server port
This is wrong. Cloudify Manager (described in `manager` object) is not DB. Cloudify Manager is core part of Cloudify. Cloudify Stage is just UI for Cloudify Manager.
Please check: https://docs.cloudify.co/5.0.0/install_maintain/installation/manager-image/ for how to install Cloudify Manager using OpenStack/AWS/Docker image.

> ```
> 2. conf/app.json
> ```
> ......
> "ssl": {
>     "ca": "" // Because error say can't find ***.pem file, so......
>   },
> ......
Not necessary to change anything in `conf/app.json`. 
`ssl.ca` will be overriden by what you defined in `me.json` file.

> 3. webpack.config.js (CopyWebpackPlugin)
> ```
>     // {
>     //     from: 'userData',
>     //     to: 'userData'
>     // }
> 
>     /* Because when run devServer, get an error say , can't find "serData" */
> ```
Thanks for notification. I'll probably add `userData` to GitHub.

For the future - please use our Slack channel: https://cloudify.co/slack/ to ask for support or report issues. Don't hesitate to contact me directly (@Jakub Niezgoda). 

For now I'm closing this Github issue.
